### ISSUE TITLE
#1264 - Guest UI: general design note 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#124]
Adjust bottom of page so we don't ever see the bottoms of the rocks - perhaps cut off the bottom 1/4 or so

**Comment by neerajkhatri-btc** [comment]
@HirenBhalani-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
As per Paul's comment:  Nope - still seeing the bottoms of the rocks.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : pls check UI in i-pad and i-phone

Availability Table Page not Proper Show in i-pad and i-phone

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  Can you please add screenshot for reference?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : pls see that

I-PAD AIR Image
![img_0118](https://cloud.githubusercontent.com/assets/16792762/14675617/7342d4d2-0727-11e6-83bb-b3f610aec636.PNG)

I-Phone 5s Image
![img_3824](https://cloud.githubusercontent.com/assets/16792762/14675618/734ab0e4-0727-11e6-97fd-7770bb898969.PNG)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
