### ISSUE TITLE
#1303 Guest UI: Event Horizon not blocking Guest UI Reservations 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#219]
Please see reservation for Eric Muritz on Dec 6-7 2016 (res ID81470 on staging). Eric was able to reserve a platform tent in December, which should be impossible.

There are two reasons he was able to do this: first, the Events team has not yet blocked out the tent and pv sites for the off season ( they do this by creating a "No Tent/No? PV" event for the whole season, and block all of those sites). This in and of itself is not a glitch. However...

Eric should not have been able to even start a reservation for that date, since it falls beyond the event horizon. I believe we allow this via the Office UI so we can book cabins for event presenters in advance, but this should not be possible via the guest UI (i.e., should not be possible for users with Guest User role).

**Comment by NishantUpadhyay-BTC** [comment]
First - at the top of the first page "Personal Retreat Availability", right under the words "CHECK SPECIFIC DATES OR BROWSE AVAILABLILTY ON THE CALENDAR." please insert the following text (in the dark green we've been using elsewhere): "We are now taking reservations through <event horizon>."

Second, text for error when user selects dates that overlap or are beyond the Event Horizon: ""We are now taking reservations through <event horizon>. The dates you've selected fall outside of this range."

**Comment by NishantUpadhyay-BTC** [comment]
For the scenario when a lodging has no rate set for a given period, it seems to me that it should not appear as "available" in the Availability Table, nor should it appear in the Available Lodgings table. Possible?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by neerajkhatri-btc** [comment]
@ManojParmar-BTC : 
1. Office UI > there r no Special Periods on this dates
2. Select date > Wed, 1-4-17 > so why 'The dates you've chosen span an 'Adults-Only' time period. The dates you've chosen span a 'Women-Only' time period.' text show?
   ![selection_416](https://cloud.githubusercontent.com/assets/16792762/15564530/da630e50-2330-11e6-9bb1-b36e10fbdd49.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
Date reference is still missing from the error message that pops up when user selects dates beyond the event horizon on the "Personal Retreat Availability" page. See attached screen shot.

Also this error only needs one button: "OK"

![eve_horizon](https://cloud.githubusercontent.com/assets/6542029/16105722/ee487a2e-33aa-11e6-956d-065bd6f88360.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
