### ISSUE TITLE
#1346 -  Guest UI: Linens not an option for PV or Own Tent sites 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#273]
We do not offer linens for guests staying in PV and Tent sites (but we do for Platform Tents). So, if one of those lodging types is chosen, linens should not appear as an option on the Reservation Details page (and also should not appear on the Reservation Summary and Thank You pages).

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
Re-opening. Linens are still showing up as an option for Additional Guests for PV site reservations. I didn't check this for tents -but please check this as well.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
